# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from uas_tasks import count_failed as count_failed
from uas_tasks import count_ingested as count_ingested
from uas_tasks import count_skipped as count_skipped
from uas_tasks import extract_results_df as extract_results_df
from uas_tasks import extract_track_gdf as extract_track_gdf
from uas_tasks import format_total_flight_time as format_total_flight_time
from uas_tasks import ingest_flights as ingest_flights
from uas_tasks import set_aircraft_identity as set_aircraft_identity
from uas_tasks import set_decimation_rate as set_decimation_rate
from uas_tasks import set_dji_api_key as set_dji_api_key
from uas_tasks import set_event_type_name as set_event_type_name
from uas_tasks import set_input_folder as set_input_folder
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    dji_api_key = (
        task(set_dji_api_key)
        .validate()
        .set_task_instance_id("dji_api_key")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("dji_api_key") or {}))
        .call()
    )

    input_folder = (
        task(set_input_folder)
        .validate()
        .set_task_instance_id("input_folder")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("input_folder") or {}))
        .call()
    )

    event_type_name = (
        task(set_event_type_name)
        .validate()
        .set_task_instance_id("event_type_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("event_type_name") or {}))
        .call()
    )

    aircraft_identity = (
        task(set_aircraft_identity)
        .validate()
        .set_task_instance_id("aircraft_identity")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("aircraft_identity") or {}))
        .call()
    )

    decimation_rate = (
        task(set_decimation_rate)
        .validate()
        .set_task_instance_id("decimation_rate")
        .handle_errors()
        .with_tracing()
        .partial(**(params.get("decimation_rate") or {}))
        .call()
    )

    ingest_result = (
        task(ingest_flights)
        .validate()
        .set_task_instance_id("ingest_result")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            dji_api_key=dji_api_key,
            input_folder=input_folder,
            event_type_name=event_type_name,
            aircraft_identity=aircraft_identity,
            decimation_rate=decimation_rate,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("ingest_result") or {}),
        )
        .call()
    )

    track_gdf = (
        task(extract_track_gdf)
        .validate()
        .set_task_instance_id("track_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(ingest_result=ingest_result, **(params.get("track_gdf") or {}))
        .call()
    )

    results_df = (
        task(extract_results_df)
        .validate()
        .set_task_instance_id("results_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(ingest_result=ingest_result, **(params.get("results_df") or {}))
        .call()
    )

    track_layer = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("track_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=track_gdf,
            tooltip_columns=["aircraft_serial", "takeoff_utc", "flight_time_min"],
            legend=None,
            layer_style={
                "color_column": "track_color",
                "get_width": 3,
                "width_units": "pixels",
                "cap_rounded": True,
            },
            **(params.get("track_layer") or {}),
        )
        .call()
    )

    flight_map = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("flight_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=[
                {
                    "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 1.0,
                    "max_zoom": 20,
                    "min_zoom": 0,
                }
            ],
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right"},
            static=False,
            max_zoom=20,
            geo_layers=track_layer,
            **(params.get("flight_map") or {}),
        )
        .call()
    )

    flight_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("flight_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="flight_tracks",
            text=flight_map,
            **(params.get("flight_map_url") or {}),
        )
        .call()
    )

    status_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("status_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=results_df,
            widget_id="Ingestion Status",
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            columns=[
                "file",
                "aircraft_serial",
                "takeoff_utc",
                "flight_time_min",
                "battery_pct_takeoff",
                "battery_pct_landing",
                "max_alt_agl_m",
                "max_speed_ms",
                "max_dist_m",
                "status",
                "error",
            ],
            **(params.get("status_table_html") or {}),
        )
        .call()
    )

    status_table_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("status_table_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ingestion_status",
            text=status_table_html,
            **(params.get("status_table_url") or {}),
        )
        .call()
    )

    stat_ingested = (
        task(count_ingested)
        .validate()
        .set_task_instance_id("stat_ingested")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(ingest_result=ingest_result, **(params.get("stat_ingested") or {}))
        .call()
    )

    stat_skipped = (
        task(count_skipped)
        .validate()
        .set_task_instance_id("stat_skipped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(ingest_result=ingest_result, **(params.get("stat_skipped") or {}))
        .call()
    )

    stat_failed = (
        task(count_failed)
        .validate()
        .set_task_instance_id("stat_failed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(ingest_result=ingest_result, **(params.get("stat_failed") or {}))
        .call()
    )

    stat_flight_time = (
        task(format_total_flight_time)
        .validate()
        .set_task_instance_id("stat_flight_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(ingest_result=ingest_result, **(params.get("stat_flight_time") or {}))
        .call()
    )

    widget_ingested = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_ingested")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Ingested",
            data=stat_ingested,
            decimal_places=0,
            **(params.get("widget_ingested") or {}),
        )
        .call()
    )

    widget_skipped = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_skipped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Skipped",
            data=stat_skipped,
            decimal_places=0,
            **(params.get("widget_skipped") or {}),
        )
        .call()
    )

    widget_failed = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_failed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Failed",
            data=stat_failed,
            decimal_places=0,
            **(params.get("widget_failed") or {}),
        )
        .call()
    )

    widget_flight_time = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_flight_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Time Flown",
            data=stat_flight_time,
            **(params.get("widget_flight_time") or {}),
        )
        .call()
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Flight Tracks",
            data=flight_map_url,
            **(params.get("map_widget") or {}),
        )
        .call()
    )

    table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Ingestion Status",
            data=status_table_url,
            **(params.get("table_widget") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            time_range=None,
            details=workflow_details,
            widgets=[
                widget_ingested,
                widget_skipped,
                widget_failed,
                widget_flight_time,
                map_widget,
                table_widget,
            ],
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
